[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.ts"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Content-Type = "image/webp"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Content-Type = "image/x-icon"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200